package main

// builtins is a map of builtin functions and their descriptions
var builtins = map[string]string{
	FORMAT:                "format input",
	READ:                  "reads input from the user",
	PRINT:                 "prints a Lisp value to the console",
	PLUS:                  "addition operation",
	MINUS:                 "subtraction operation",
	STAR:                  "multiplication operation",
	SLASH:                 "division operation",
	PERCENT:               "modulo operation",
	POW:                   "pow operation",
	SQRT:                  "sqrt operation",
	CONCAT:                "concat operation",
	SUBSTRING:             "substring operation",
	IS_NUMBER:             "isNumber operation",
	IS_STRING:             "isString operation",
	LESS_THAN:             "less than condition",
	LESS_OR_EQUAL_THAN:    "less or equal than condition",
	GREATER_THAN:          "greater than condition",
	GREATER_OR_EQUAL_THAN: "greater or equal than condition",
	EQUAL:                 "equal to condition",
	IF:                    "if conditional struct",
	DEFUN:                 "function definition",
	LAMBDA:                "lambda function definition",
	LET:                   "let local variable definition",
	AND:                   "and logical operation",
	OR:                    "or logical operation",
	NOT:                   "not logical operation",
	LIST:                  "list definition",
	CAR:                   "car list operation. It retrieves first element of a list.",
	CDR:                   "cdr list operation. It retrieves the rest elements of a list.",
	CONS:                  "cons list operation. It add element to a list.",
	LENGTH:                "length list operation. It retrieves the length of a list.",
	APPEND:                "append list operation. It add a list to another list.",
}
